// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace testTPIData.Models;

public partial class CineDbContext : DbContext
{
    public CineDbContext(DbContextOptions<CineDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Butaca> Butacas { get; set; }

    public virtual DbSet<ClasificacionesEdad> ClasificacionesEdads { get; set; }

    public virtual DbSet<Cliente> Clientes { get; set; }

    public virtual DbSet<Contacto> Contactos { get; set; }

    public virtual DbSet<Entrada> Entradas { get; set; }

    public virtual DbSet<FormasCompra> FormasCompras { get; set; }

    public virtual DbSet<FormasPago> FormasPagos { get; set; }

    public virtual DbSet<Funcione> Funciones { get; set; }

    public virtual DbSet<Genero> Generos { get; set; }

    public virtual DbSet<GenerosXpelicula> GenerosXpeliculas { get; set; }

    public virtual DbSet<Idioma> Idiomas { get; set; }

    public virtual DbSet<Pelicula> Peliculas { get; set; }

    public virtual DbSet<Promocione> Promociones { get; set; }

    public virtual DbSet<Reserva> Reservas { get; set; }

    public virtual DbSet<Sala> Salas { get; set; }

    public virtual DbSet<TiposButaca> TiposButacas { get; set; }

    public virtual DbSet<TiposContacto> TiposContactos { get; set; }

    public virtual DbSet<TiposDoc> TiposDocs { get; set; }

    public virtual DbSet<TiposEntradum> TiposEntrada { get; set; }

    public virtual DbSet<TiposSala> TiposSalas { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Butaca>(entity =>
        {
            entity.HasKey(e => e.IdButaca).HasName("pk_butacas");

            entity.ToTable("butacas");

            entity.Property(e => e.IdButaca).HasColumnName("id_butaca");
            entity.Property(e => e.Columna).HasColumnName("columna");
            entity.Property(e => e.Fila)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("fila");
            entity.Property(e => e.IdSala).HasColumnName("id_sala");
            entity.Property(e => e.IdTipoButaca).HasColumnName("id_tipo_butaca");

            entity.HasOne(d => d.IdSalaNavigation).WithMany(p => p.Butacas)
                .HasForeignKey(d => d.IdSala)
                .HasConstraintName("fk_butacas_salas");

            entity.HasOne(d => d.IdTipoButacaNavigation).WithMany(p => p.Butacas)
                .HasForeignKey(d => d.IdTipoButaca)
                .HasConstraintName("fk_butacas_tipo");
        });

        modelBuilder.Entity<ClasificacionesEdad>(entity =>
        {
            entity.HasKey(e => e.IdClasEdad).HasName("pk_clasificaciones_edad");

            entity.ToTable("clasificaciones_edad");

            entity.Property(e => e.IdClasEdad).HasColumnName("id_clas_edad");
            entity.Property(e => e.Clasificacion)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("clasificacion");
        });

        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.IdCliente).HasName("pk_clientes");

            entity.ToTable("clientes");

            entity.Property(e => e.IdCliente).HasColumnName("id_cliente");
            entity.Property(e => e.Apellido)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("apellido");
            entity.Property(e => e.FecAfiliacion)
                .HasColumnType("datetime")
                .HasColumnName("fec_afiliacion");
            entity.Property(e => e.IdTipoDoc).HasColumnName("id_tipo_doc");
            entity.Property(e => e.Nombre)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre");
            entity.Property(e => e.NumeroDoc).HasColumnName("numero_doc");

            entity.HasOne(d => d.IdTipoDocNavigation).WithMany(p => p.Clientes)
                .HasForeignKey(d => d.IdTipoDoc)
                .HasConstraintName("fk_clientes_tipos_doc");
        });

        modelBuilder.Entity<Contacto>(entity =>
        {
            entity.HasKey(e => e.IdContacto).HasName("pk_contactos");

            entity.ToTable("contactos");

            entity.Property(e => e.IdContacto).HasColumnName("id_contacto");
            entity.Property(e => e.Contacto1)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("contacto");
            entity.Property(e => e.IdCliente).HasColumnName("id_cliente");
            entity.Property(e => e.IdTipoContacto).HasColumnName("id_tipo_contacto");

            entity.HasOne(d => d.IdClienteNavigation).WithMany(p => p.Contactos)
                .HasForeignKey(d => d.IdCliente)
                .HasConstraintName("fk_contactos_clientes");

            entity.HasOne(d => d.IdTipoContactoNavigation).WithMany(p => p.Contactos)
                .HasForeignKey(d => d.IdTipoContacto)
                .HasConstraintName("fk_contactos_tipos");
        });

        modelBuilder.Entity<Entrada>(entity =>
        {
            entity.HasKey(e => new { e.IdButaca, e.IdFuncion }).HasName("pk_entradas");

            entity.ToTable("entradas");

            entity.Property(e => e.IdButaca).HasColumnName("id_butaca");
            entity.Property(e => e.IdFuncion).HasColumnName("id_funcion");
            entity.Property(e => e.IdPromocion).HasColumnName("id_promocion");
            entity.Property(e => e.IdReserva).HasColumnName("id_reserva");
            entity.Property(e => e.IdTipoEntrada).HasColumnName("id_tipo_entrada");
            entity.Property(e => e.Precio)
                .HasColumnType("money")
                .HasColumnName("precio");

            entity.HasOne(d => d.IdButacaNavigation).WithMany(p => p.Entrada)
                .HasForeignKey(d => d.IdButaca)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_entradas_butacas");

            entity.HasOne(d => d.IdFuncionNavigation).WithMany(p => p.Entrada)
                .HasForeignKey(d => d.IdFuncion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_entradas_funciones");

            entity.HasOne(d => d.IdPromocionNavigation).WithMany(p => p.Entrada)
                .HasForeignKey(d => d.IdPromocion)
                .HasConstraintName("fk_entradas_promociones");

            entity.HasOne(d => d.IdReservaNavigation).WithMany(p => p.Entrada)
                .HasForeignKey(d => d.IdReserva)
                .HasConstraintName("fk_entradas_reservas");

            entity.HasOne(d => d.IdTipoEntradaNavigation).WithMany(p => p.Entrada)
                .HasForeignKey(d => d.IdTipoEntrada)
                .HasConstraintName("fk_entradas_tipos");
        });

        modelBuilder.Entity<FormasCompra>(entity =>
        {
            entity.HasKey(e => e.IdFormaCompra).HasName("pk_formas_compra");

            entity.ToTable("formas_compra");

            entity.Property(e => e.IdFormaCompra).HasColumnName("id_forma_compra");
            entity.Property(e => e.FormaCompra)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("forma_compra");
        });

        modelBuilder.Entity<FormasPago>(entity =>
        {
            entity.HasKey(e => e.IdFormaPago).HasName("pk_formas_pago");

            entity.ToTable("formas_pago");

            entity.Property(e => e.IdFormaPago).HasColumnName("id_forma_pago");
            entity.Property(e => e.FormaPago)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("forma_pago");
        });

        modelBuilder.Entity<Funcione>(entity =>
        {
            entity.HasKey(e => e.IdFuncion).HasName("pk_funciones");

            entity.ToTable("funciones");

            entity.Property(e => e.IdFuncion).HasColumnName("id_funcion");
            entity.Property(e => e.FechaAlta)
                .HasColumnType("datetime")
                .HasColumnName("fecha_alta");
            entity.Property(e => e.Horario)
                .HasColumnType("datetime")
                .HasColumnName("horario");
            entity.Property(e => e.IdIdioma).HasColumnName("id_idioma");
            entity.Property(e => e.IdPelicula).HasColumnName("id_pelicula");
            entity.Property(e => e.IdSala).HasColumnName("id_sala");
            entity.Property(e => e.PrecioActual)
                .HasColumnType("money")
                .HasColumnName("precio_actual");
            entity.Property(e => e.Subtitulada).HasColumnName("subtitulada");

            entity.HasOne(d => d.IdIdiomaNavigation).WithMany(p => p.Funciones)
                .HasForeignKey(d => d.IdIdioma)
                .HasConstraintName("fk_funciones_idiomas");

            entity.HasOne(d => d.IdPeliculaNavigation).WithMany(p => p.Funciones)
                .HasForeignKey(d => d.IdPelicula)
                .HasConstraintName("fk_funciones_peliculas");

            entity.HasOne(d => d.IdSalaNavigation).WithMany(p => p.Funciones)
                .HasForeignKey(d => d.IdSala)
                .HasConstraintName("fk_funciones_salas");
        });

        modelBuilder.Entity<Genero>(entity =>
        {
            entity.HasKey(e => e.IdGenero).HasName("pk_generos");

            entity.ToTable("generos");

            entity.Property(e => e.IdGenero).HasColumnName("id_genero");
            entity.Property(e => e.Genero1)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("genero");
        });

        modelBuilder.Entity<GenerosXpelicula>(entity =>
        {
            entity.HasKey(e => e.IdGeneroPelicula).HasName("pk_generos_peliculas");

            entity.ToTable("generosXpeliculas");

            entity.Property(e => e.IdGeneroPelicula).HasColumnName("id_genero_pelicula");
            entity.Property(e => e.IdGenero).HasColumnName("id_genero");
            entity.Property(e => e.IdPelicula).HasColumnName("id_pelicula");

            entity.HasOne(d => d.IdGeneroNavigation).WithMany(p => p.GenerosXpeliculas)
                .HasForeignKey(d => d.IdGenero)
                .HasConstraintName("fk_generos_peliculas_genero");

            entity.HasOne(d => d.IdPeliculaNavigation).WithMany(p => p.GenerosXpeliculas)
                .HasForeignKey(d => d.IdPelicula)
                .HasConstraintName("fk_generos_peliculas_peliculas");
        });

        modelBuilder.Entity<Idioma>(entity =>
        {
            entity.HasKey(e => e.IdIdioma).HasName("pk_idiomas");

            entity.ToTable("idiomas");

            entity.Property(e => e.IdIdioma).HasColumnName("id_idioma");
            entity.Property(e => e.Idioma1)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("idioma");
        });

        modelBuilder.Entity<Pelicula>(entity =>
        {
            entity.HasKey(e => e.IdPelicula).HasName("pk_peliculas");

            entity.ToTable("peliculas");

            entity.Property(e => e.IdPelicula).HasColumnName("id_pelicula");
            entity.Property(e => e.Duracion).HasColumnName("duracion");
            entity.Property(e => e.FechaBaja)
                .HasColumnType("date")
                .HasColumnName("fecha_baja");
            entity.Property(e => e.FechaEstreno)
                .HasColumnType("date")
                .HasColumnName("fecha_estreno");
            entity.Property(e => e.IdClasEdad).HasColumnName("id_clas_edad");
            entity.Property(e => e.Pelicula1)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("pelicula");
            entity.Property(e => e.Sinopsis)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("sinopsis");

            entity.HasOne(d => d.IdClasEdadNavigation).WithMany(p => p.Peliculas)
                .HasForeignKey(d => d.IdClasEdad)
                .HasConstraintName("fk_peliculas_clasificacion");
        });

        modelBuilder.Entity<Promocione>(entity =>
        {
            entity.HasKey(e => e.IdPromocion).HasName("pk_promociones");

            entity.ToTable("promociones");

            entity.Property(e => e.IdPromocion).HasColumnName("id_promocion");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("descripcion");
            entity.Property(e => e.Descuento)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("descuento");
        });

        modelBuilder.Entity<Reserva>(entity =>
        {
            entity.HasKey(e => e.IdReserva).HasName("pk_reservas");

            entity.ToTable("reservas");

            entity.Property(e => e.IdReserva).HasColumnName("id_reserva");
            entity.Property(e => e.EstadoPago).HasColumnName("estado_pago");
            entity.Property(e => e.FechaEmision)
                .HasColumnType("datetime")
                .HasColumnName("fecha_emision");
            entity.Property(e => e.FechaPago)
                .HasColumnType("datetime")
                .HasColumnName("fecha_pago");
            entity.Property(e => e.IdCliente).HasColumnName("id_cliente");
            entity.Property(e => e.IdFormaCompra).HasColumnName("id_forma_compra");
            entity.Property(e => e.IdFormaPago).HasColumnName("id_forma_pago");

            entity.HasOne(d => d.IdClienteNavigation).WithMany(p => p.Reservas)
                .HasForeignKey(d => d.IdCliente)
                .HasConstraintName("fk_reservas_clientes");

            entity.HasOne(d => d.IdFormaCompraNavigation).WithMany(p => p.Reservas)
                .HasForeignKey(d => d.IdFormaCompra)
                .HasConstraintName("fk_reservas_formas_compra");

            entity.HasOne(d => d.IdFormaPagoNavigation).WithMany(p => p.Reservas)
                .HasForeignKey(d => d.IdFormaPago)
                .HasConstraintName("fk_reservas_formas_pago");
        });

        modelBuilder.Entity<Sala>(entity =>
        {
            entity.HasKey(e => e.IdSala).HasName("pk_salas");

            entity.ToTable("salas");

            entity.Property(e => e.IdSala).HasColumnName("id_sala");
            entity.Property(e => e.Activa).HasColumnName("activa");
            entity.Property(e => e.IdTipoSala).HasColumnName("id_tipo_sala");

            entity.HasOne(d => d.IdTipoSalaNavigation).WithMany(p => p.Salas)
                .HasForeignKey(d => d.IdTipoSala)
                .HasConstraintName("fk_salas_tipos_salas");
        });

        modelBuilder.Entity<TiposButaca>(entity =>
        {
            entity.HasKey(e => e.IdTipoButaca).HasName("pk_tipos_butacas");

            entity.ToTable("tipos_butacas");

            entity.Property(e => e.IdTipoButaca).HasColumnName("id_tipo_butaca");
            entity.Property(e => e.TipoButaca)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("tipo_butaca");
        });

        modelBuilder.Entity<TiposContacto>(entity =>
        {
            entity.HasKey(e => e.IdTipoContacto).HasName("pk_tipos_contactos");

            entity.ToTable("tipos_contactos");

            entity.Property(e => e.IdTipoContacto).HasColumnName("id_tipo_contacto");
            entity.Property(e => e.TipoContacto)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("tipo_contacto");
        });

        modelBuilder.Entity<TiposDoc>(entity =>
        {
            entity.HasKey(e => e.IdTipoDoc).HasName("pk_tipos_doc");

            entity.ToTable("tipos_doc");

            entity.Property(e => e.IdTipoDoc).HasColumnName("id_tipo_doc");
            entity.Property(e => e.TipoDoc)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("tipo_doc");
        });

        modelBuilder.Entity<TiposEntradum>(entity =>
        {
            entity.HasKey(e => e.IdTipoEntrada).HasName("pk_tipos_entrada");

            entity.ToTable("tipos_entrada");

            entity.Property(e => e.IdTipoEntrada).HasColumnName("id_tipo_entrada");
            entity.Property(e => e.TipoEntrada)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("tipo_entrada");
        });

        modelBuilder.Entity<TiposSala>(entity =>
        {
            entity.HasKey(e => e.IdTipoSala).HasName("pk_tipos_salas");

            entity.ToTable("tipos_salas");

            entity.Property(e => e.IdTipoSala).HasColumnName("id_tipo_sala");
            entity.Property(e => e.TipoSala)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("tipo_sala");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}