// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace testTPIData.Models;

public partial class Entrada
{
    public int IdButaca { get; set; }

    public int IdFuncion { get; set; }

    public int? IdReserva { get; set; }

    public int? IdPromocion { get; set; }

    public int? IdTipoEntrada { get; set; }

    public decimal? Precio { get; set; }

    public virtual Butaca IdButacaNavigation { get; set; }

    public virtual Funcione IdFuncionNavigation { get; set; }

    public virtual Promocione IdPromocionNavigation { get; set; }

    public virtual Reserva IdReservaNavigation { get; set; }

    public virtual TiposEntradum IdTipoEntradaNavigation { get; set; }
}