// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace testTPIData.Models;

public partial class GenerosXpelicula
{
    public int IdGeneroPelicula { get; set; }

    public int? IdGenero { get; set; }

    public int? IdPelicula { get; set; }

    public virtual Genero IdGeneroNavigation { get; set; }

    public virtual Pelicula IdPeliculaNavigation { get; set; }
}