// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using testTPIData.Models;

namespace testTPIData.Models
{
    public partial interface ICineDbContextProcedures
    {
        Task<List<INGRESOS_MENSUALES_X_FUNCResult>> INGRESOS_MENSUALES_X_FUNCAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<PELICULAS_ATP_BARATO_Y_CAROResult>> PELICULAS_ATP_BARATO_Y_CAROAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<RecuperarCapacidadYEntradasVendidasResult>> RecuperarCapacidadYEntradasVendidasAsync(int? id_funcion, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<RecuperarFuncionesNoSubtituladasHoyResult>> RecuperarFuncionesNoSubtituladasHoyAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<RecuperarFuncionesSubtituladasHoyResult>> RecuperarFuncionesSubtituladasHoyAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_PELICULAS_ENT_FUNCResult>> SP_PELICULAS_ENT_FUNCAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_RESUMEN_POSICIONESResult>> SP_RESUMEN_POSICIONESAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<TOP10Result>> TOP10Async(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
