// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace testTPIData.Models;

public partial class Idioma
{
    public int IdIdioma { get; set; }

    public string Idioma1 { get; set; }

    public virtual ICollection<Funcione> Funciones { get; set; } = new List<Funcione>();
}