// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace testTPIData.Models
{
    public partial class INGRESOS_MENSUALES_X_FUNCResult
    {
        public int codigo_funcion { get; set; }
        public int? anio { get; set; }
        [Column("ingresos_totales", TypeName = "decimal(38,6)")]
        public decimal? ingresos_totales { get; set; }
        public int? clientes_asociados { get; set; }
    }
}
