// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace testTPIData.Models;

public partial class Pelicula
{
    public int IdPelicula { get; set; }

    public int? IdClasEdad { get; set; }

    public string Pelicula1 { get; set; }

    public TimeSpan? Duracion { get; set; }

    public string Sinopsis { get; set; }

    public DateTime? FechaEstreno { get; set; }

    public DateTime? FechaBaja { get; set; }

    public virtual ICollection<Funcione> Funciones { get; set; } = new List<Funcione>();

    public virtual ICollection<GenerosXpelicula> GenerosXpeliculas { get; set; } = new List<GenerosXpelicula>();

    public virtual ClasificacionesEdad IdClasEdadNavigation { get; set; }
}