// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace testTPIData.Models
{
    public partial class PELICULAS_ATP_BARATO_Y_CAROResult
    {
        public string pelicula { get; set; }
        public string sinopsis { get; set; }
        public int? Cantidad_Funciones { get; set; }
        public decimal? Precio { get; set; }
        public string Tipo { get; set; }
    }
}
