// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace testTPIData.Models;

public partial class Promocione
{
    public int IdPromocion { get; set; }

    public decimal? Descuento { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Entrada> Entrada { get; set; } = new List<Entrada>();
}