// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace testTPIData.Models
{
    public partial class RecuperarFuncionesNoSubtituladasHoyResult
    {
        public int id_funcion { get; set; }
        public DateTime? horario { get; set; }
        public int? Sala { get; set; }
        public string pelicula { get; set; }
        public bool? subtitulada { get; set; }
    }
}
