// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace testTPIData.Models;

public partial class Reserva
{
    public int IdReserva { get; set; }

    public int? IdFormaPago { get; set; }

    public int? IdCliente { get; set; }

    public int? IdFormaCompra { get; set; }

    public DateTime? FechaEmision { get; set; }

    public DateTime? FechaPago { get; set; }

    public bool? EstadoPago { get; set; }

    public virtual ICollection<Entrada> Entrada { get; set; } = new List<Entrada>();

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual FormasCompra IdFormaCompraNavigation { get; set; }

    public virtual FormasPago IdFormaPagoNavigation { get; set; }
}