// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace testTPIData.Models;

public partial class Sala
{
    public int IdSala { get; set; }

    public int? IdTipoSala { get; set; }

    public bool? Activa { get; set; }

    public virtual ICollection<Butaca> Butacas { get; set; } = new List<Butaca>();

    public virtual ICollection<Funcione> Funciones { get; set; } = new List<Funcione>();

    public virtual TiposSala IdTipoSalaNavigation { get; set; }
}