// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace testTPIData.Models
{
    public partial class SP_RESUMEN_POSICIONESResult
    {
        public string Posicion { get; set; }
        [Column("Entradas Totales")]
        public int? EntradasTotales { get; set; }
        [Column("Frecuencia de ocupacion")]
        public double? Frecuenciadeocupacion { get; set; }
        [Column("Frecuencia de ocupacion normalizada")]
        public double? Frecuenciadeocupacionnormalizada { get; set; }
        [Column("Frecuencia de ocupacion estandarizada")]
        public double? Frecuenciadeocupacionestandarizada { get; set; }
    }
}
