// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace testTPIData.Models;

public partial class TiposButaca
{
    public int IdTipoButaca { get; set; }

    public string TipoButaca { get; set; }

    public virtual ICollection<Butaca> Butacas { get; set; } = new List<Butaca>();
}