// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace testTPIData.Models;

public partial class TiposEntradum
{
    public int IdTipoEntrada { get; set; }

    public string TipoEntrada { get; set; }

    public virtual ICollection<Entrada> Entrada { get; set; } = new List<Entrada>();
}