// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace testTPIData.Models;

public partial class TiposDoc
{
    public int IdTipoDoc { get; set; }

    public string TipoDoc { get; set; }

    public virtual ICollection<Cliente> Clientes { get; set; } = new List<Cliente>();
}