// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace testTPIData.Models
{
    public partial class TOP10Result
    {
        public int id_pelicula { get; set; }
        public string Titulo { get; set; }
        [Column("Entradas Vendidas")]
        public int? EntradasVendidas { get; set; }
        public string Estado { get; set; }
    }
}
